name: Python application

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      - name: Lint
        run: pip install flake8 && flake8
      - name: Validate import sort order
        run: pip install isort && isort --check --quiet
      - name: Validate formatting
        run: pip install black && black --check --quiet .
      # - name: Test with pytest
      #   run: |
      #     pip install pytest
      #     pytest
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Typecheck
        run: pip install mypy && mypy --strict > /dev/null
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: README is up-to-date
        run: python ./gen/mkreadme.py --check
